# Generated by Django 3.2.6 on 2021-08-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0002_auto_20210823_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
