# Generated by Django 3.2.6 on 2021-09-27 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0006_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='limited_integer_field',
            new_name='priority',
        ),
    ]
