# Generated by Django 4.0 on 2022-01-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0006_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='unsyncedSource',
            field=models.CharField(default='', max_length=50),
        ),
    ]
