# Generated by Django 4.0.2 on 2022-02-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0008_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
