version: '3.7'

services:
  web:
    build: ./rosecore
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./rosecore:/usr/src/rosecore:Z
    ports:
      - 80:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - rosecore
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/:rw
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    networks:
      - rosecore
volumes:
  postgres_data:

networks:
  rosecore: