version: '3.7'

services:
  web:
    build: ./rosecore
    command: gunicorn RoseCore.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 80:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/:rw
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
